# Generated by Django 4.1.2 on 2022-10-19 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='score.vote'),
        ),
    ]
