# Generated by Django 4.1.2 on 2022-10-19 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0005_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_field', to='score.menu'),
        ),
    ]
