# Generated by Django 4.1.2 on 2022-10-19 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0006_scores_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='voter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voter_field', to='score.employee'),
        ),
    ]
